# On quarto websites, see https://quarto.org/docs/reference/projects/websites.html
# On publishing with github pages, see https://quarto.org/docs/publishing/github-pages.html
project:
  type: website
  output-dir: docs

# see https://quarto.org/docs/websites/website-navigation.html
website:
  title: "PubPol 000"
  navbar:
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: assignments.qmd
        text: Assignment Guide
      - href: slides
        text: Slides

format:
 html:
   toc: true
   toc-location: left
   theme: michigan.scss
   css: styles.css


number-depth: 3

# bibliography: xxx.bib
